### PR TITLE
Update columnstore-indexes-overview.md

### PR DESCRIPTION
**Pull request by uniqalex**
repaired the translate of the columnstore and rowstore descriptions

### CODE REVIEW

**Comment by mauriciomoravia** [comment]
Hi @uniqalex , we are still in discussing, will update the decision later soon. 

Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @uniqalex , kindly sign the CLA so we can merge your suggestions

Thank you

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@uniqalex , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Comment by uniqalex** [comment]
Sorry for timeout in singing CLA. If may be needed I'll try to help to validate document translation again)

**Pull request merged**
